### ISSUE TITLE
Schedules table

### ISSUE THREAD

**Issue by GambuzX** [NIAEFEUP/tts-revamp-fe#1]
Recreate the current table for the schedules, as is here: https://ni.fe.up.pt/TTS/

**Comment by TiagooGomess** [comment]
Maybe I'll use [React Scheduler](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/getting-started/)

**Comment by TiagooGomess** [comment]
After some testing, I found out that [React Scheduler](https://devexpress.github.io/devextreme-reactive/react/scheduler/) is not what we want. Its focus is on appointment scheduling, which is not what we want. We need to build the timetable from scratch.
