### ISSUE TITLE
Repeated classes for multiple lessons

### ISSUE THREAD

**Issue by Jumaruba** [NIAEFEUP/tts-revamp-fe#103]
The mechanics course, for example, has the multiple practical lessons for one class. 
Both classes should appear compiled in just one option in the menu.

![image](https://user-images.githubusercontent.com/33182421/187934282-5645853d-f1f6-4c4e-8c9e-b55aa478fe3f.png)

**Comment by SergioEstevao11** [comment]
Being analyses in the issue #135, since we still don't know how valuable this feature is
