### ISSUE TITLE
Extra-UCs: Selection List Box not showing all UCs during modal

### ISSUE THREAD

**Issue by SergioEstevao11** [NIAEFEUP/tts-revamp-fe#133]
While selecting the extra UCs, the SelectionListBox will only show the Extra UCs instead of all selected UCs. The User should be able to see all the UCs during this phase, like in the main selection modal, as depicted in the third image:

(1) During the Selection Modal:
![image](https://user-images.githubusercontent.com/63104941/216784696-d377fcbe-4a40-409d-8038-86f417ecea50.png)

(2) During the Extra UCs Selection Modal:
![image](https://user-images.githubusercontent.com/63104941/216784739-079efb3b-1750-4a72-a989-e9f211f572e3.png)

(3) After the selection, the UCs show up in the main Selection modal as wanted:
![image](https://user-images.githubusercontent.com/63104941/216784900-f4ef3bc3-dffb-45ef-a6bf-1d1d47caacb9.png)

**Comment by tomaspalma** [comment]
Hello, since the creation of this issue, it has been solved in the #121 pull request linked to the #112 issue.
