### ISSUE TITLE
[FEUPExchange] Form for student to change the schedule

### ISSUE THREAD

**Issue by Jumaruba** [NIAEFEUP/tts-revamp-fe#22]
Create component to change the schedule: 
![image](https://user-images.githubusercontent.com/33182421/146805450-2560ee10-5d0f-4475-a889-238682d9005a.png)

Use the [link](https://github.com/NIAEFEUP/subject-trade/blob/master/src/state/student.py) to get the reference to parameters.

**Comment by EduRibeiro00** [comment]
After this issue is resolved, please create an issue to implement this page.
