### ISSUE TITLE
Add images to the home page 

### ISSUE THREAD

**Issue by Jumaruba** [NIAEFEUP/tts-revamp-fe#25]
The home page contains some images, but they are not set. 
So, your task is to choose and add beautiful images to the home page. 
![image](https://user-images.githubusercontent.com/33182421/147880446-9514061d-2d6e-41c0-aa81-d257f282b08b.png)

**Comment by AFKFLEX** [comment]
![image](https://user-images.githubusercontent.com/93888436/148045467-ebdb1349-cfdc-43a4-bcc3-b93d5af9bace.png)

Fiz uma imagem mockup  no photoshop e inseri no ficheiro imagens . Depois dei import e tentei chamar a imagem dentro do container , só  que devo estar a fazer qualquer coisa de errado que a imagem não aparece .

**Comment by AFKFLEX** [comment]
![image](https://user-images.githubusercontent.com/93888436/148048501-1150a87f-3ef7-450d-a9dc-0402964b66d0.png)

**Comment by AFKFLEX** [comment]
já consegui , ficou assim

**Comment by AFKFLEX** [comment]
Two Images Added to HomePage . Currently stored in the images folder and imported to homepage as homepage1.png and homepage2.jpg
