### ISSUE TITLE
[FEUPExchange] Create mockup for the student page after the deadline

### ISSUE THREAD

**Issue by EduRibeiro00** [NIAEFEUP/tts-revamp-fe#27]
The execution of the allocation algorithm will be scheduled by the platform administrators to a certain date and time. Students will be able to register, use and edit their allocation preferences until roughly 5 minutes before the execution deadline. After the deadline, the student preferences will be "locked in", and every student that tries to access FEUPExchange should be greeted with a page that informs them that the deadline has been reached, and that they can no longer modify their preferences.

After this issue is resolved, please create an issue to implement this page.

**Comment by marianalt** [comment]
Here it is a possible mockup for this purpose
<img src="https://user-images.githubusercontent.com/76732179/163999023-30644005-070d-4a35-bfaa-562399419356.png" width="800" >
