### ISSUE TITLE
[FEUPExchange] Implement instructions/disclaimer/FAQ page

### ISSUE THREAD

**Issue by EduRibeiro00** [NIAEFEUP/tts-revamp-fe#29]
FEUPExchange should provide its users with a page that gives a detailed explanation of what the platform is, what is its purpose and what problems it is attempting to solve.

It should also provide bullet points with detailed instructions of how a student can use our platform to get a better schedule than the one they currently have. In those instructions, the student needs to understand that they will have a deadline (related to the datetime of the algorithm execution), after which they will NOT be able to modify their preferences or erase their participation.

The page should also have a disclaimer section, so that the student understands that FEUPExchange only promises to give the student a schedule that is inside its preferences (targets, give-ins, and buddies), and does not promise the student their "perfect" schedule. As long as the new schedule is within the student's preferences, FEUPExchange is not responsible if the student prefers its old schedule when compared to the new one.

Finally, the page should also have a brief FAQ section, in which we will answer some commonly asked questions that students might have regarding the platform.

**Comment by srissirs** [comment]
Hi! So I've done some mockups for the page and I'd like your opinion as to what to change or improve.
I decided to put the FAQ section in a diferent page for the time being, so the page wouldn't get too cluttered, but if you think it would be better to keep them all in the same page please tell and I'll make the necessary changes.

Note: The majority of the text is just a fill-in.

![image](https://user-images.githubusercontent.com/80845032/159953863-a26ad60f-7b13-4294-9fe0-e50ba9ca8ac1.png)

FAQ page

![image](https://user-images.githubusercontent.com/80845032/159954022-bd93857a-a84e-4484-82f1-b49d19bf38ec.png)

**Comment by EduRibeiro00** [comment]
I think it's better to have the FAQ on another page. The design of the FAQ page also seems pretty good!

Regarding the other page, I think the "What is FEUPExchange?" section looks good on the top of the page, displaying a brief description of the product and what is its use. For the "How to use FEUPExchange correctly?" section, the only thing I would change is making it an ordered list instead of just simple bullet points. It could also be a bit more complex and visual, but for the time being, I think there is no need, this design looks good. Finally, the disclaimer section also looks good, but we need to have into account that it is a very important message that all users should be aware of. I think there's no problem in putting the disclaimer at the bottom of the page, but I think we should also put the disclaimer in a place where everybody can see it, either on the home page or on the page where the student picks their preferences. This way we are 100% sure the students are aware of the disclaimer.

Just another thing to have into account, initially this platform is going to be in Portuguese, so all text should be in Portuguese.

What do you think @Jumaruba and @kiko-g ?

**Comment by kiko-g** [comment]
Totally agree with what @EduRibeiro00 said. Nevertheless great work!
