### ISSUE TITLE
Create FAQ for the TTS

### ISSUE THREAD

**Issue by Jumaruba** [NIAEFEUP/tts-revamp-fe#86]
The current FAQ page is related to FEUP Exchange. However, for the next release, these FAQs don't bring useful information and might confuse the user, since it is a product that is not yet available.

Thus, the FEUP Exchange FAQ should be hidden and extra information about the TTS should be added to the FAQ. 

- [x] Refactored FAQs page component
- [x] FEUP Exchange FAQs content is hidden
- [x] Time Table  Selector FAQs content is ready
- [x] Move help from the more actions menu to the bottom of the sidebar

**Comment by kiko-g** [comment]
#85 also adds a help button to the more actions menu.
![image](https://user-images.githubusercontent.com/40745490/183691838-9b53516a-abcc-4156-8882-8b057fe48907.png)
![image](https://user-images.githubusercontent.com/40745490/183691934-aff50fdb-6807-45ef-a203-c1f0288b8e66.png)
